services:
  - type: web
    name: funda-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 app:app"
    healthCheckPath: "/"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: funda-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.10"

databases:
  - name: funda-db
    databaseName: funda
    user: funda_user